<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnjoyEveryday.Application\EnjoyEveryday.Application.csproj" />
    <ProjectReference Include="..\EnjoyEveryday.Infrastructure\EnjoyEveryday.Infrastructure.csproj" />
    <ProjectReference Include="..\EnjoyEveryday.Shared\EnjoyEveryday.Shared.csproj" />
  </ItemGroup>

</Project>
